### ISSUE TITLE
NoMethodError: undefined method `spec' for nil:NilClass

### ISSUE THREAD

**Issue by rajrathore** [medihack/make_flaggable#31]
I'm using this gem from rails3 and now I'm using rails 4 and it's not working. Installing it gives "NoMethodError: undefined method `spec' for nil:NilClass"
```
NoMethodError: undefined method `spec' for nil:NilClass
/Users/raj/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/site_ruby/2.0.0/rubygems/installer.rb:254:in `spec'
/Users/raj/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/site_ruby/2.0.0/rubygems/installer.rb:739:in `build_extensions'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/source/path.rb:188:in `generate_bin'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/source/git.rb:166:in `install'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:104:in `block in install_gem_from_spec'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/rubygems_integration.rb:162:in `with_build_args'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:103:in `install_gem_from_spec'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:264:in `block in install_sequentially'
/Users/raj/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/forwardable.rb:171:in `each'
/Users/raj/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/forwardable.rb:171:in `each'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:263:in `install_sequentially'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:90:in `run'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/installer.rb:18:in `install'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/cli/install.rb:78:in `run'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/cli.rb:145:in `install'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/command.rb:27:in `run'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/base.rb:440:in `start'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/cli.rb:9:in `start'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/bin/bundle:20:in `block in <top (required)>'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/bin/bundle:18:in `<top (required)>'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/bin/bundle:23:in `load'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@global/bin/bundle:23:in `<main>'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@blog/bin/ruby_executable_hooks:15:in `eval'
/Users/raj/.rvm/gems/ruby-2.0.0-p576@blog/bin/ruby_executable_hooks:15:in `<main>'
An error occurred while installing make_flaggable (0.0.3), and Bundler cannot
continue.
```

**Comment by rajrathore** [comment]
Successfully installed the gem after updating bundler.
